### ISSUE TITLE
Debounce when "going up".

### ISSUE THREAD

**Issue by yunjova** [poelstra/arduino-multi-button#1]
The debouncing is only doen when going to pressed state. There can also be bouncing when going up (e.g. some relay contacts can bounce in either way the switch goes).

So it would be good to add debouncing for the up and otherup states.

Kind regards,

**Comment by yunjova** [comment]
I did not experience any difficulties yet (only tried the lib with one button as an experiment).

What I mean is: that the release is not debounced/deglitched and a glitch (single reading) will go from StatePressed to StateClickUp (in function _checkPressed).
Then if it was a glitch and further readings are 'pressed', the result becomes a doubleclick iso of e.g. a longpress.

**Comment by poelstra** [comment]
It is assumed that once the button is 'fully pressed' (i.e. pressed for more than `DEBOUNCE_DELAY`, it will keep being pressed until it is released. Once it begins to be released, it may bounce a few times until it becomes 'fully released'. These new bounces will be handled by either the `DoubleClickDebounce` or `Debounce` states.

Suppose the first (and second) part of the following pattern is long enough to be detected as a click, but too short for a long click (e.g. every character is 5ms):

```
##########_##########
```

Then, indeed, that very short interruption will make the second part be detected as a double-click. This is intended behavior.

Do you have a type of switch that will glitch while being pressed?

**Comment by yunjova** [comment]
Potential glitch from long lines (pushbuttons in the home to control lights, ...). The lines can be up to 10 m maybe 15 m. It's a project to be build. I have no idea yet if there will be glitches (due to EMI, ...) and what form they will have. I just want to be sure that it is possible to have some defense (in software) if needed.

**Comment by poelstra** [comment]
Ah. Note that if you're using momentary push buttons, these will be 'open' most of the time. Any glitch that will happen then, is going to be filtered out already.
Also, when pushing the button, it will be a low-impedance path (direct connection to ground, as opposed to the pull-up resistor to Vcc when not being pushed). This also lowers the chance for a glitch.
As such, I don't think you'll ever have issues with it.

However, it is of course possible to add deglitch on everything. If I have some time, I'll add it to a future version, just in case. Might also improve things for e.g. noisy capacitive touch switches.

**Comment by yunjova** [comment]
OK, thanks. Indeed, for mechanical buttons, there is little chance to have a glitch ("caused by the line") while the button is pressed.
