### ISSUE TITLE
Two buttons pressed

### ISSUE THREAD

**Issue by jotamachuca** [poelstra/arduino-multi-button#5]
Hi

I have a question. I need catch the event when I press two buttons at the same time. How can implements ?

THanks in advance

**Comment by poelstra** [comment]
I suppose something like this would work? (untested...)

```cpp
void loop() {
  button1.update();
  button2.update();

  static bool button1Pressed = false;
  static bool button2Pressed = false;

  if (button1.isClick()) {
    button1Pressed = true;
  } else if (button1.isReleased()) {
    button1Pressed = false;
  }

  if (button2.isClick()) {
    button2Pressed = true;
  } else if (button2.isReleased()) {
    button2Pressed = false;
  }

  if (button1.isClick() && button2Pressed || button2.isClick() && button1Pressed) {
    Serial.println("Both buttons pressed");
  }
}
```

Arguably, it would be nice if there would be a `isPressed()` method, which would prevent having to manually keep the buttonXPressed states, but it's not there right now, sorry ;)
